services:
  app:
    build: .
    environment:
      MY_SECRET_KEY: 'use django.core.management.utils.get_random_secret_key to generate your secret key'
      MY_STORAGE_DIR: /storage
    ports:
      - 80:80
    volumes:
      - storage:/storage
    restart: unless-stopped

volumes:
  storage:
