services:
  app:
    build: .
    environment:
      - MY_SECRET_KEY
      - MY_STORAGE_DIR=/storage
    volumes:
      - storage:/storage
    restart: unless-stopped
    labels:
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"

  traefik:
    image: traefik:latest
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

volumes:
  storage:
