services:
  app:
    build: .
    environment:
      - MY_SECRET_KEY
      - MY_STORAGE_DIR=/storage
    ports:
      - 80:80
    volumes:
      - storage:/storage
    restart: unless-stopped

volumes:
  storage:
