services:
  app:
    build: .
    environment:
      - MY_SECRET_KEY
      - MY_STORAGE_DIR=/storage
    volumes:
      - storage:/storage
    restart: unless-stopped

  caddy:
    image: caddy:latest
    command: caddy reverse-proxy --from ${MY_HOSTNAME} --to app:80
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
    restart: unless-stopped

volumes:
  storage:
  caddy:
